print "   ******    *******"
print "  *      *   *      *"
print "  *      *   *       *"
print "  *          *       *"
print "   *         *      *"
print "    Shane    Berthoud"
print "         *   *      *"
print "          *  *       *"
print "  *       *  *       *"
print "  *       *  *      *"
print "   *******   *******"

