def strip_word( w ):
    w = replace( w, ".", "" )
    w = replace( w, ",", "" )
    w = replace( w, ";", "" )
    w = replace( w, ":", "" )
    w = replace( w, "'", "" )
    w = replace( w, "&", "" )
    w = replace( w, "\n", "" )
    w = w.lower()
    return( w )
